version: '3'

services: 

  back-end:
    build: 
      context: node-proj
    container_name: back-end
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./node-proj:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3001:3001"
    command: npm run start
    

  front-end:
    build: 
      context: react-proj/testapp
    container_name: front-end
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./react-proj/testapp:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3002:3002"
    command: npm run start

  nnginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - node-network
    depends_on:
       - back-end
       - front-end
  
networks: 
  node-network:
    driver: bridge
    